/// <reference types="node" />

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"

import type { ParityResult, VisualOs } from "./visual.types.ts"
import { VisualSettings } from "./VisualSettings.ts"

/**
 * `--parity`'s report:  collects the spec's `ParityResult` files (`tools/results/visual/<os>/parity/<browser>/`)
 * into `tools/results/visual/parity.md`, one table per OS and browser, most different first.
 * - Informational only:  the class-grammar original and the element markup aren't pixel-identical (headings,
 *   wrappers, shorthands), so a difference is a lead to look at, not a failure.
 */
export class ParityReport {
  /** Remove `os`'s previous results, so the report never mixes runs. */
  static clear(os: VisualOs) {
    rmSync(ParityReport.folder(os), { recursive: true, force: true })
  }

  /** Write the report for `oses`;  returns its path. */
  static write(oses: readonly VisualOs[]): string {
    const { threshold, ratio } = VisualSettings.PARITY
    const lines = [
      "# Parity:  class grammar vs elements",
      "",
      `Generated by \`yarn test:visual --parity\`, ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC.`,
      "Each example's class-grammar original (`examples/<name>.html`) against its element markup",
      "(`examples/elements/<name>.html`), light scheme.  Informational:  the two markups are not pixel-identical.",
      "",
      `- a pixel differs when a channel differs by more than ${threshold} of 255`,
      `- a pair is listed as DIFFERENT above ${(ratio * 100).toFixed(1)}% differing pixels (size changes count)`,
      "- diff images:  red = differing pixel, over a faded copy of the element render",
      ""
    ]
    for (const os of oses) {
      const folder = ParityReport.folder(os)
      if (!existsSync(folder)) continue
      for (const browser of readdirSync(folder).sort()) {
        const results = readdirSync(`${folder}/${browser}`)
          .filter((file) => file.endsWith(".json"))
          .map((file) => JSON.parse(readFileSync(`${folder}/${browser}/${file}`, "utf8")) as ParityResult)
          .sort((a, b) => b.ratio - a.ratio)
        const different = results.filter((result) => result.ratio > ratio)
        lines.push(`## ${VisualSettings.osFolder(os)} / ${browser}`, "")
        lines.push(`${different.length} of ${results.length} pairs differ.`, "")
        lines.push("| Example | Classes (w x h) | Elements (w x h) | Differing | Diff |", "|---|--:|--:|--:|---|")
        for (const result of results) lines.push(ParityReport.row(result))
        lines.push("")
      }
    }
    mkdirSync(VisualSettings.RESULTS, { recursive: true })
    const file = `${VisualSettings.RESULTS}/parity.md`
    writeFileSync(file, `${lines.join("\n")}\n`)
    return file
  }

  /** One table row. */
  private static row(result: ParityResult): string {
    const size = ({ width, height }: { width: number; height: number }) => `${width} x ${height}`
    const percent = `${(result.ratio * 100).toFixed(2)}%`
    const diff = result.diff ? `[diff](${result.diff})` : ""
    return `| \`${result.id}\` | ${size(result.classes)} | ${size(result.elements)} | ${percent} | ${diff} |`
  }

  /** Results folder of `os`. */
  private static folder(os: VisualOs): string {
    return `${VisualSettings.RESULTS}/${VisualSettings.osFolder(os)}/parity`
  }
}
