services:
  app-server-dev:
    env_file:
      - docker.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - spell-network

  api-server:
    env_file:
      - docker.env
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - spell-network

networks:
  spell-network:
    driver: bridge
