import {
  ICON_NAMES_ATTRIBUTE,
  type IconAliasMap,
  type IconData,
  type IconEntry,
  type IconNames,
  type IconNamesIndex,
  type IconResolved,
  type IconStyle
} from "./icons.types"

/** Namespace for SVG element creation -- `document.createElementNS()` needs it, `createElement()` doesn't apply. */
const SVG_NS = "http://www.w3.org/2000/svg"

/**
 * Runtime-side loader for Font Awesome 7 Free icon data generated by `scripts/gen-icons.ts`.
 * - Framework-agnostic:  every method works with plain data (`IconData` tuples) except `svg()`, the one
 *   place that touches the DOM.
 * - Static-only class (no instances) -- there's exactly one icon dataset per page, same shape as `UI`'s
 *   singleton services, but simple enough not to need `new`.
 * - ONE ES MODULE PER ICON (`glyphs/<style>/<name>.js`, `export default [w, h, "path"]`):  `get()` computes
 *   the URL from the resolved name and `import()`s it.  There is NO name -> loader map, so a bundler neither
 *   inlines the glyphs nor emits 2000 entries -- the glyph files just have to be served next to the built
 *   module (see `docs/icons.md`, "Shipping icons").  The module system is the cache:  a URL evaluates once
 *   per page, even across two bundles.
 * - The small lookup data (`names.json`, the three alias maps) is lazy too and cached forever after.
 * - `resolve()` is `async`:  telling a bare, style-less name apart (`solid` vs `brands`) needs the names
 *   index, and the alias maps are lazy.  `peek()` stays fully synchronous by only ever answering from what's
 *   ALREADY cached:  it returns `undefined` for a name that needs an alias map or the names index before those
 *   have loaded, same as for an unloaded glyph.  `preload()` warms both.
 * - `register()` puts a statically imported glyph in the same cache, the tree-shakable path for apps that
 *   only use a few icons.
 */
export class Icons {
  /** `<style>/<name>` -> that icon's load state.  Shared across every `get()` caller;  `register()` writes here too. */
  static #icons = new Map<string, IconEntry>()

  /**
   * Base URL of the `glyphs/` directory, if the files are NOT next to the built module.
   * - Empty (default) ~== `glyphs/` next to the module containing `Icons`, via `import.meta.url`.
   * - e.g. `Icons.glyphBase = "https://cdn.example.com/ui/glyphs/"`.  MUST end with `/`.
   * - Read on every load:  set it before the first `get()`.
   */
  static glyphBase = ""

  /** `names.json`, once loaded -- `undefined` until the first lookup that needs it. */
  static #namesLoader: Promise<IconNamesIndex> | undefined
  /** `names.json` as `Set`s, built with it (name membership is the hot check in every lookup). */
  static #nameSets: Record<IconStyle, Set<string>> | undefined

  /** The three alias maps, once loaded -- `undefined` until the first lookup that needs one. */
  static #aliasesLoader: Promise<AliasMaps> | undefined
  static #aliases: AliasMaps | undefined

  /**
   * Sorted words -> the ONE icon they name in any order, or `null` if 2+ icons share them
   * (`arrow-up-a-z` / `arrow-up-z-a`).
   * - Built on first use from the solid names + Font Awesome's aliases -- see `#reorder()`.
   */
  static #wordSets: Map<string, string | null> | undefined

  ////////////////
  // ## Name resolution
  ////////////////

  /**
   * Resolves a possibly-aliased, possibly-multi-word icon name to its canonical Font Awesome 7 name + style.
   * - Spaces ~== dashes:  `"tablet button"` ~== `"tablet-button"`,  `"sign-in"` ~== `"sign in"`.
   * - Order:  strip a trailing `outline` word (-> `style: "regular"`), then Fomantic's OWN alias vocabulary
   *   (`"mail"` -> `"envelope"`, `"setting"` -> `"gear"`), then Font Awesome's alias vocabulary
   *   (`"cog"` -> `"gear"`), then -- if `style` is still unknown -- checks the (lazily-loaded) names index:
   *   present there => `solid`, otherwise => `brands`.  A name Font Awesome doesn't know at all resolves as
   *   `solid` anyway;  `get()` then correctly finds nothing and returns `undefined`.
   * - Last resort, word order:  a name found nowhere is tried in ANY order, if those words name exactly one
   *   icon -- `"button tablet"` -> `"tablet-button"` -- see `#reorder()`.
   * - `style`, whether passed in or inferred from `outline`, always wins over the solid/brands guess --
   *   a caller who says `{ style: "brands" }` is trusted, even for a name that also happens to exist elsewhere.
   * - A word that means different icons in the two vocabularies (`"x"`, `"warning"`, `"sign in"` ...)
   *   gets Font Awesome's meaning, unless the page opts into Fomantic's -- see `preferredNames`.
   */
  static async resolve(name: string, style?: IconStyle): Promise<IconResolved> {
    const aliases = await Icons.#loadAliases()
    const partial = Icons.#resolveAliases(name, style, aliases)
    if (partial.style === "brands") return { name: partial.name, style: "brands" }
    await Icons.#loadNames()
    const found = Icons.#reorder(partial.name, Icons.#nameSets!.solid, aliases.fa)
    return { name: found, style: partial.style ?? (Icons.#isSolid(found) ? "solid" : "brands") }
  }

  /**
   * `name`, or the one icon its words name in another order -- `"button-tablet"` -> `"tablet-button"`.
   * - Only for a name the solid names don't include:  an exact name, Fomantic alias or FA alias always wins.
   * - Ambiguous word sets (`a-z` vs `z-a`, `left-right` vs `right-left`) stay as typed, so they fail loudly
   *   rather than silently picking one.
   * - NOTE: covers solid + regular (every regular icon is also solid) and brands only through FA's aliases
   *   (`github-square` -> `square-github`) -- reordering brands would need their whole name list.
   *   `Icons.test.ts` checks no real brand name is ever redirected.
   */
  static #reorder(name: string, solid: ReadonlySet<string>, faAliases: IconAliasMap): string {
    if (solid.has(name) || !name.includes("-")) return name
    Icons.#wordSets ??= Icons.#buildWordSets(solid, faAliases)
    return Icons.#wordSets.get(Icons.#wordSet(name)) ?? name
  }

  /** `#wordSets` from every multi-word solid name and Font Awesome alias. */
  static #buildWordSets(solid: ReadonlySet<string>, faAliases: IconAliasMap): Map<string, string | null> {
    const sets = new Map<string, string | null>()
    const entries = [...[...solid].map((key) => [key, key]), ...Object.entries(faAliases)]
    for (const [key, target] of entries) {
      if (!key.includes("-")) continue
      const words = Icons.#wordSet(key)
      const current = sets.get(words)
      sets.set(words, current === undefined || current === target ? target : null)
    }
    return sets
  }

  /** Order-free key for a dashed name:  its words, sorted -- `"tablet-button"` -> `"button tablet"`. */
  static #wordSet(name: string): string {
    return name.split("-").sort().join(" ")
  }

  /**
   * The synchronous, cache-only half of `resolve()` -- alias lookups only, no chunk loading.
   * - Shared by `resolve()` (which awaits `#loadAliases()` first, so `aliases` is always populated there)
   *   and `peek()` (which passes whatever's already cached -- `undefined` maps just fall through to the
   *   dashed name unchanged, same as a name with no alias at all).
   */
  static #resolveAliases(
    name: string,
    style: IconStyle | undefined,
    aliases: AliasMaps | undefined
  ): { name: string; style?: IconStyle } {
    const words = name
      .trim()
      .toLowerCase()
      .split(/[\s-]+/)
      .filter(Boolean)
    let resolvedStyle = style
    if (!resolvedStyle && words.at(-1) === "outline") {
      resolvedStyle = "regular"
      words.pop()
    }
    const phrase = words.join(" ")
    const kebab = words.join("-")
    const clash = aliases && Icons.preferredNames === "fomantic" ? aliases.fomanticClashes[phrase] : undefined
    const afterFomantic = clash ?? aliases?.fomantic[phrase] ?? kebab
    const canonical = aliases?.fa[afterFomantic] ?? afterFomantic
    return { name: canonical, style: resolvedStyle }
  }

  /**
   * Which vocabulary wins a clash, read from `<html ui-icon-names>` on EVERY lookup.
   * - `"fontawesome"` unless the attribute says `"fomantic"`;  also outside a browser (no `document`).
   * - NOTE: flipping the attribute affects later lookups only -- icons already drawn keep their old meaning.
   */
  static get preferredNames(): IconNames {
    if (typeof document === "undefined") return "fontawesome"
    return document.documentElement.getAttribute(ICON_NAMES_ATTRIBUTE) === "fomantic" ? "fomantic" : "fontawesome"
  }

  ////////////////
  // ## Data access
  ////////////////

  /**
   * Resolves `name` and loads its glyph module (once per icon, cached after), returning its
   * `[width, height, path]` tuple -- `undefined` for a name Font Awesome doesn't have in that style.
   * - Unknown names never hit the network:  the names index is checked before any `import()`.
   */
  static async get(name: string, style?: IconStyle): Promise<IconData | undefined> {
    // An explicit style is trusted BEFORE aliasing:  `("apple", "brands")` means the Apple logo, not the
    // Fomantic alias `apple` -> `apple-whole` (solid), which has no brands entry at all.
    if (style) {
      const plain = await Icons.#lookup(Icons.#kebab(name), style)
      if (plain) return plain
    }
    // Fast path:  an exact Font Awesome name needs no alias maps (~28 KB gzip), because in the default
    // vocabulary an exact name always resolves to itself.  Fomantic mode can remap it (`x`), so it skips this.
    if (!style && Icons.preferredNames !== "fomantic") {
      const exact = await Icons.#exactStyle(Icons.#kebab(name))
      if (exact) return Icons.#lookup(Icons.#kebab(name), exact)
    }
    const request = await Icons.resolve(name, style)
    return Icons.#lookup(request.name, request.style)
  }

  /** `solid` or `brands` if `name` is exactly an icon there (solid wins, as in `resolve()`), else `undefined`. */
  static async #exactStyle(name: string): Promise<IconStyle | undefined> {
    await Icons.#loadNames()
    if (Icons.#isSolid(name)) return "solid"
    return Icons.#nameSets!.brands.has(name) || Icons.#icons.has(`brands/${name}`) ? "brands" : undefined
  }

  /**
   * Registers a statically imported glyph, so `get()` / `peek()` answer for it without any request.
   * - The tree-shakable path:  `import user from "@spell/ui/icons/glyphs/solid/user.js"` +
   *   `Icons.register("user", user)` bundles just that icon.
   * - Also how an app adds its OWN icon:  any `name` works, it needn't exist in Font Awesome.
   * - Replaces whatever was loaded or registered under the same `name` + `style`;  `name` is normalized like
   *   a lookup (`"Circle Check"` ~== `"circle-check"`), but not aliased.
   * - SIDE EFFECT:  shared page-wide cache, there is no unregister.
   */
  static register(name: string, data: IconData, style: IconStyle = "solid"): void {
    Icons.#icons.set(`${style}/${Icons.#kebab(name)}`, { promise: Promise.resolve(data), data })
  }

  /** The glyph behind `get()`:  the cached or freshly imported tuple of `name` in `style`, if that icon exists. */
  static async #lookup(name: string, style: IconStyle): Promise<IconData | undefined> {
    const cached = Icons.#icons.get(`${style}/${name}`)
    if (cached) return cached.promise
    await Icons.#loadNames()
    if (!Icons.#nameSets![style].has(name)) return undefined
    return Icons.#loadGlyph(name, style)
  }

  /** `name` normalized the way the glyph files spell it:  lowercase words joined with `-`. */
  static #kebab(name: string): string {
    return name
      .trim()
      .toLowerCase()
      .split(/[\s-]+/)
      .filter(Boolean)
      .join("-")
  }

  /**
   * Whether `name` is a solid icon:  in the names index, or `register()`ed as solid.
   * - `#nameSets` MUST be loaded when `resolve()` calls this.
   */
  static #isSolid(name: string): boolean {
    return Icons.#nameSets?.solid.has(name) === true || Icons.#icons.has(`solid/${name}`)
  }

  /**
   * Synchronous counterpart to `get()`:  returns the tuple if that icon has ALREADY been loaded (by an
   * earlier `get()` or `preload()`) or `register()`ed, `undefined` otherwise -- never triggers a fetch itself.
   * - Uses only the synchronous alias/style resolution:  if the style is still ambiguous (no explicit
   *   `style`, no `outline` word) it looks for the name loaded as `solid`, then as `brands`, rather than
   *   guessing from an index that may not have loaded yet.
   */
  static peek(name: string, style?: IconStyle): IconData | undefined {
    if (style) {
      // same explicit-style-first rule as `get()`
      const plain = Icons.#icons.get(`${style}/${Icons.#kebab(name)}`)?.data
      if (plain) return plain
    }
    const partial = Icons.#resolveAliases(name, style, Icons.#aliases)
    const solid = Icons.#nameSets?.solid
    const found =
      solid && partial.style !== "brands" ? Icons.#reorder(partial.name, solid, Icons.#aliases?.fa ?? {}) : partial.name
    const resolvedStyle = partial.style ?? (Icons.#isSolid(found) ? "solid" : Icons.#nameSets ? "brands" : undefined)
    if (resolvedStyle) return Icons.#icons.get(`${resolvedStyle}/${found}`)?.data
    // names index not loaded yet:  answer only if the icon is cached under some style
    return Icons.#icons.get(`brands/${found}`)?.data
  }

  /**
   * Warms the cache for `names` (each resolved with its default style), plus the alias maps and the names
   * index -- fire-and-forget from a component, or from a parent list before rendering slotted icons.
   * - Warming the alias maps explicitly (not just as a side effect of `get()`) means `preload([])` still
   *   readies `peek()` for exact FA7 names, and `Icons.resolve()` inside the loop below never re-fetches
   *   them per name -- `#loadAliases()` / `#loadNames()` cache their own promise.
   */
  static async preload(names: readonly string[]): Promise<void> {
    await Promise.all([Icons.#loadAliases(), Icons.#loadNames(), ...names.map((name) => Icons.get(name))])
  }

  /**
   * Every icon name available in `style`, sorted, for the docs site's icon browser.
   * - `async` because the names index is lazy (`names.json`, ~29 KB).
   * - Font Awesome's names only:  `register()`ed icons are not listed.
   */
  static async names(style: IconStyle): Promise<string[]> {
    return [...(await Icons.#loadNames())[style]]
  }

  ////////////////
  // ## Lazy data loading
  ////////////////

  /**
   * Loads (once) and caches the three alias maps -- `aliases.json` (Font Awesome's own), `fomantic-aliases.json`
   * and `fomantic-clashes.json`.  Every `resolve()` call awaits this;  `peek()` instead reads `#aliases`
   * straight from cache, `undefined` until this has resolved at least once.
   * - Literal specifiers (not a template):  each file becomes its own lazy chunk instead of landing in the
   *   eager bundle of every component that renders an icon.
   */
  static async #loadAliases(): Promise<AliasMaps> {
    Icons.#aliasesLoader ??= Promise.all([
      import("./data/aliases.json"),
      import("./data/fomantic-aliases.json"),
      import("./data/fomantic-clashes.json")
    ]).then(([fa, fomantic, fomanticClashes]) => {
      const maps: AliasMaps = {
        fa: fa.default as IconAliasMap,
        fomantic: fomantic.default as IconAliasMap,
        fomanticClashes: fomanticClashes.default as IconAliasMap
      }
      Icons.#aliases = maps
      return maps
    })
    return Icons.#aliasesLoader
  }

  /** Loads (once) and caches `names.json`, plus its `Set` form -- what every solid-vs-brands guess checks. */
  static async #loadNames(): Promise<IconNamesIndex> {
    Icons.#namesLoader ??= import("./data/names.json").then((module) => {
      const names = module.default as IconNamesIndex
      Icons.#nameSets = {
        solid: new Set(names.solid),
        regular: new Set(names.regular),
        brands: new Set(names.brands)
      }
      return names
    })
    return Icons.#namesLoader
  }

  /**
   * Imports (once) `glyphs/<style>/<name>.js`.
   * - The URL is computed, and `import()` is `@vite-ignore`d:  a bundler must NOT see a pattern here, or it
   *   would emit (or inline) every glyph.  `name` comes from the names index, so it's always a safe slug.
   * - A failed import (offline, glyphs not deployed) is forgotten, so a later `get()` retries.
   */
  static #loadGlyph(name: string, style: IconStyle): Promise<IconData | undefined> {
    const key = `${style}/${name}`
    const url = new URL(`glyphs/${key}.js`, Icons.glyphBase || Icons.#moduleUrl).href
    // NOTE: `entry` is built before `promise` so the `.then()` closure can fill in `entry.data` once the
    // import settles -- `peek()` reads that same object back out of `#icons`, no separate bookkeeping.
    const entry = {} as IconEntry
    entry.promise = import(/* @vite-ignore */ url).then(
      (module: { default: IconData }) => (entry.data = module.default),
      (error: unknown) => {
        Icons.#icons.delete(key)
        throw error
      }
    )
    Icons.#icons.set(key, entry)
    return entry.promise
  }

  /** URL of the module containing `Icons` -- the default place to look for `glyphs/`.  Own getter so the bundler leaves it alone. */
  static get #moduleUrl(): string {
    return import.meta.url
  }

  ////////////////
  // ## Rendering
  ////////////////

  /**
   * Builds an `<svg>` element for `data` (from `get()` / `peek()`):  its `viewBox` plus a single
   * `<path fill="currentColor">`, so CSS `color` drives the icon's colour same as text.
   * - No `label` (the common case, a purely decorative icon next to visible text) => `aria-hidden="true"`,
   *   so screen readers skip it.
   * - A `label` => `role="img"` + `aria-label`, making the icon itself the accessible name (for an icon-only
   *   control with no visible text).
   * - `title` adds an `<svg><title>` for a native tooltip -- independent of `label`, since a labelled icon
   *   can still want hover text.
   */
  static svg(data: IconData, options: { label?: string; title?: string } = {}): SVGSVGElement {
    const [width, height, path] = data
    const svg = document.createElementNS(SVG_NS, "svg")
    svg.setAttribute("viewBox", `0 0 ${width} ${height}`)
    if (options.label) {
      svg.setAttribute("role", "img")
      svg.setAttribute("aria-label", options.label)
    } else {
      svg.setAttribute("aria-hidden", "true")
    }
    if (options.title) {
      const title = document.createElementNS(SVG_NS, "title")
      title.textContent = options.title
      svg.append(title)
    }
    const path_ = document.createElementNS(SVG_NS, "path")
    path_.setAttribute("fill", "currentColor")
    path_.setAttribute("d", path)
    svg.append(path_)
    return svg
  }

  /**
   * `svg()`'s string equivalent, for templating into `innerHTML` -- e.g. a component's shadow-root template
   * literal, where creating a live element up front would be wasted work.
   * - Always `aria-hidden`:  a templated icon has no `label`/`title` slot -- a caller that needs those
   *   builds with `svg()` instead, or wraps the string in its own labelled container.
   * - Path data is digits / letters / spaces / punctuation only (SVG path grammar), never a quote or `<` --
   *   safe to inline without escaping.
   */
  static svgString(data: IconData): string {
    const [width, height, path] = data
    return `<svg viewBox="0 0 ${width} ${height}" aria-hidden="true"><path fill="currentColor" d="${path}"/></svg>`
  }
}

/** The three alias maps `#loadAliases()` loads together, cached as one unit on `Icons.#aliases`. */
type AliasMaps = {
  /** `aliases.json` -- Font Awesome's own alternate names. */
  fa: IconAliasMap
  /** `fomantic-aliases.json` -- Fomantic's vocabulary, where it differs from FA7 and doesn't clash. */
  fomantic: IconAliasMap
  /** `fomantic-clashes.json` -- Fomantic names that clash with a Font Awesome one;  opt-in only. */
  fomanticClashes: IconAliasMap
}
