import faAliases from "./data/aliases.json"
import fomanticAliases from "./data/fomantic-aliases.json"
import type {
  IconAliasMap,
  IconChunk,
  IconChunkIndex,
  IconData,
  IconLoader,
  IconResolved,
  IconStyle
} from "./icons.types"

/** Namespace for SVG element creation -- `document.createElementNS()` needs it, `createElement()` doesn't apply. */
const SVG_NS = "http://www.w3.org/2000/svg"

/**
 * Runtime-side loader for Font Awesome 7 Free icon data generated by `scripts/gen-icons.ts`.
 * - Framework-agnostic:  every method works with plain data (`IconData` tuples) except `svg()`, the one
 *   place that touches the DOM.
 * - Static-only class (no instances) -- there's exactly one icon dataset per page, same shape as `UI`'s
 *   singleton services, but simple enough not to need `new`.
 * - Data loading is lazy and cached PER CHUNK:  `aliases.json` + `fomantic-aliases.json` are small enough
 *   (~38 KB together) to import statically above, but `solid.json` (the chunk index, ~36 KB) and every
 *   `solid-*` / `regular` / `brands` data file are dynamically imported on first use and cached forever
 *   after -- see `docs/icons.md` for the full size table and why the split lands here rather than at the
 *   40 KB line the brief suggested (`regular.json` and `brands.json` turned out to be 111 KB / 478 KB,
 *   not "small").
 * - `resolve()` is `async` (not sync, despite reading as one in casual use like `await Icons.resolve(...)`):
 *   disambiguating a bare, style-less name between `solid` and `brands` needs the chunk index, which is
 *   itself lazy.  `peek()` stays fully synchronous by only ever answering from what's ALREADY cached.
 */
export class Icons {
  /** Chunk name ("solid-a-c", "regular", "brands") -> its load state.  Shared across every `get()` caller. */
  static #chunks = new Map<string, IconLoader>()

  /** The `solid.json` chunk index, once loaded -- `undefined` until the first `solid`-style lookup. */
  static #solidIndexLoader: Promise<IconChunkIndex> | undefined
  static #solidIndex: IconChunkIndex | undefined

  ////////////////
  // ## Name resolution
  ////////////////

  /**
   * Resolves a possibly-aliased, possibly-multi-word icon name to its canonical Font Awesome 7 name + style.
   * - Order:  strip a trailing `outline` word (-> `style: "regular"`), then Fomantic's OWN alias vocabulary
   *   (`"sign in"` -> `"right-to-bracket"`, `"mail"` -> `"envelope"`), then Font Awesome's alias vocabulary
   *   (`"cog"` -> `"gear"`), then -- if `style` is still unknown -- checks the (lazily-loaded) solid index:
   *   present there => `solid`, otherwise => `brands`.  A name Font Awesome doesn't know at all resolves as
   *   `solid` anyway;  `get()` then correctly finds nothing and returns `undefined`.
   * - `style`, whether passed in or inferred from `outline`, always wins over the solid/brands guess --
   *   a caller who says `{ style: "brands" }` is trusted, even for a name that also happens to exist elsewhere.
   */
  static async resolve(name: string, style?: IconStyle): Promise<IconResolved> {
    const partial = Icons.#resolveAliases(name, style)
    if (partial.style) return { name: partial.name, style: partial.style }
    const index = await Icons.#loadSolidIndex()
    return { name: partial.name, style: partial.name in index ? "solid" : "brands" }
  }

  /**
   * The synchronous, cache-only half of `resolve()` -- alias lookups only, no chunk loading.
   * - Shared by `resolve()` (which fills in a missing `style` with an async index check) and `peek()`
   *   (which instead leaves `style` unset when it can't answer without loading something).
   */
  static #resolveAliases(name: string, style: IconStyle | undefined): { name: string; style?: IconStyle } {
    const words = name.trim().toLowerCase().split(/\s+/).filter(Boolean)
    let resolvedStyle = style
    if (!resolvedStyle && words.at(-1) === "outline") {
      resolvedStyle = "regular"
      words.pop()
    }
    const phrase = words.join(" ")
    const kebab = phrase.replace(/ /g, "-")
    const afterFomantic = (fomanticAliases as IconAliasMap)[phrase] ?? kebab
    const canonical = (faAliases as IconAliasMap)[afterFomantic] ?? afterFomantic
    return { name: canonical, style: resolvedStyle }
  }

  ////////////////
  // ## Data access
  ////////////////

  /**
   * Resolves `name` and loads whichever chunk holds it (once per chunk, cached after), returning its
   * `[width, height, path]` tuple -- `undefined` for a name Font Awesome doesn't have in that style.
   */
  static async get(name: string, style?: IconStyle): Promise<IconData | undefined> {
    const request = await Icons.resolve(name, style)
    const chunk = request.style === "solid" ? (await Icons.#loadSolidIndex())[request.name] : request.style
    if (!chunk) return undefined
    const data = await Icons.#loadChunk(chunk)
    return data[request.name]
  }

  /**
   * Synchronous counterpart to `get()`:  returns the tuple if its chunk has ALREADY been loaded (by an
   * earlier `get()` or `preload()`), `undefined` otherwise -- never triggers a fetch itself.
   * - Uses only the synchronous alias/style resolution:  if the style is still ambiguous (no explicit
   *   `style`, no `outline` word, and the solid index hasn't loaded yet to check), this returns `undefined`
   *   rather than guessing -- there's nothing in cache to answer from either way.
   */
  static peek(name: string, style?: IconStyle): IconData | undefined {
    const partial = Icons.#resolveAliases(name, style)
    let resolvedStyle = partial.style
    if (!resolvedStyle) {
      if (!Icons.#solidIndex) return undefined
      resolvedStyle = partial.name in Icons.#solidIndex ? "solid" : "brands"
    }
    const chunk = resolvedStyle === "solid" ? Icons.#solidIndex?.[partial.name] : resolvedStyle
    if (!chunk) return undefined
    return Icons.#chunks.get(chunk)?.data?.[partial.name]
  }

  /** Warms the cache for `names` (each resolved with its default style) -- fire-and-forget from a component. */
  static async preload(names: readonly string[]): Promise<void> {
    await Promise.all(names.map((name) => Icons.get(name)))
  }

  /**
   * Every icon name available in `style`, for the docs site's icon browser.
   * - `async`, unlike a naive "just read the index" expectation:  `solid`'s names come from the (lazy)
   *   chunk index, `regular` / `brands`' names come from loading their one data file (there's no separate
   *   names-only manifest for those -- see `docs/icons.md`).
   */
  static async names(style: IconStyle): Promise<string[]> {
    if (style === "solid") return Object.keys(await Icons.#loadSolidIndex())
    return Object.keys(await Icons.#loadChunk(style))
  }

  ////////////////
  // ## Chunk loading
  ////////////////

  /** Loads (once) and caches `solid.json`, the `{ name: chunkFile }` index every solid-style lookup needs. */
  static async #loadSolidIndex(): Promise<IconChunkIndex> {
    Icons.#solidIndexLoader ??= import("./data/solid.json").then((module) => {
      const index = module.default as IconChunkIndex
      Icons.#solidIndex = index
      return index
    })
    return Icons.#solidIndexLoader
  }

  /** Loads (once) and caches one data chunk by file name (without `.json`), e.g. `"solid-a-c"`, `"brands"`. */
  static async #loadChunk(chunk: string): Promise<IconChunk> {
    const cached = Icons.#chunks.get(chunk)
    if (cached) return cached.promise
    // NOTE: `entry` is built before `promise` so the `.then()` closure can fill in `entry.data` once the
    // import settles -- `peek()` reads that same object back out of `#chunks`, no separate bookkeeping.
    const entry = {} as IconLoader
    entry.promise = import(`./data/${chunk}.json`).then((module) => {
      const data = module.default as IconChunk
      entry.data = data
      return data
    })
    Icons.#chunks.set(chunk, entry)
    return entry.promise
  }

  ////////////////
  // ## Rendering
  ////////////////

  /**
   * Builds an `<svg>` element for `data` (from `get()` / `peek()`):  its `viewBox` plus a single
   * `<path fill="currentColor">`, so CSS `color` drives the icon's colour same as text.
   * - No `label` (the common case, a purely decorative icon next to visible text) => `aria-hidden="true"`,
   *   so screen readers skip it.
   * - A `label` => `role="img"` + `aria-label`, making the icon itself the accessible name (for an icon-only
   *   control with no visible text).
   * - `title` adds an `<svg><title>` for a native tooltip -- independent of `label`, since a labelled icon
   *   can still want hover text.
   */
  static svg(data: IconData, options: { label?: string; title?: string } = {}): SVGSVGElement {
    const [width, height, path] = data
    const svg = document.createElementNS(SVG_NS, "svg")
    svg.setAttribute("viewBox", `0 0 ${width} ${height}`)
    if (options.label) {
      svg.setAttribute("role", "img")
      svg.setAttribute("aria-label", options.label)
    } else {
      svg.setAttribute("aria-hidden", "true")
    }
    if (options.title) {
      const title = document.createElementNS(SVG_NS, "title")
      title.textContent = options.title
      svg.append(title)
    }
    const path_ = document.createElementNS(SVG_NS, "path")
    path_.setAttribute("fill", "currentColor")
    path_.setAttribute("d", path)
    svg.append(path_)
    return svg
  }

  /**
   * `svg()`'s string equivalent, for templating into `innerHTML` -- e.g. a component's shadow-root template
   * literal, where creating a live element up front would be wasted work.
   * - Always `aria-hidden`:  a templated icon has no `label`/`title` slot -- a caller that needs those
   *   builds with `svg()` instead, or wraps the string in its own labelled container.
   * - Path data is digits / letters / spaces / punctuation only (SVG path grammar), never a quote or `<` --
   *   safe to inline without escaping.
   */
  static svgString(data: IconData): string {
    const [width, height, path] = data
    return `<svg viewBox="0 0 ${width} ${height}" aria-hidden="true"><path fill="currentColor" d="${path}"/></svg>`
  }
}
