import faAliases from "./data/aliases.json"
import fomanticAliases from "./data/fomantic-aliases.json"
import fomanticClashes from "./data/fomantic-clashes.json"
import {
  ICON_NAMES_ATTRIBUTE,
  type IconAliasMap,
  type IconChunk,
  type IconChunkIndex,
  type IconData,
  type IconLoader,
  type IconNames,
  type IconResolved,
  type IconStyle
} from "./icons.types"

/** Namespace for SVG element creation -- `document.createElementNS()` needs it, `createElement()` doesn't apply. */
const SVG_NS = "http://www.w3.org/2000/svg"

/**
 * Runtime-side loader for Font Awesome 7 Free icon data generated by `scripts/gen-icons.ts`.
 * - Framework-agnostic:  every method works with plain data (`IconData` tuples) except `svg()`, the one
 *   place that touches the DOM.
 * - Static-only class (no instances) -- there's exactly one icon dataset per page, same shape as `UI`'s
 *   singleton services, but simple enough not to need `new`.
 * - Data loading is lazy and cached PER CHUNK:  the three alias maps are small enough (~40 KB together)
 *   to import statically above, but `solid.json` (the chunk index, ~37 KB) and every `solid-*` / `regular` /
 *   `brands` data file are dynamically imported on first use and cached forever after -- see
 *   `docs/icons.md` for the full size table and why the split lands here.
 * - `resolve()` is `async` (not sync, despite reading as one in casual use like `await Icons.resolve(...)`):
 *   disambiguating a bare, style-less name between `solid` and `brands` needs the chunk index, which is
 *   itself lazy.  `peek()` stays fully synchronous by only ever answering from what's ALREADY cached.
 */
export class Icons {
  /** Chunk name ("solid-a-c", "regular", "brands") -> its load state.  Shared across every `get()` caller. */
  static #chunks = new Map<string, IconLoader>()

  /** The `solid.json` chunk index, once loaded -- `undefined` until the first `solid`-style lookup. */
  static #solidIndexLoader: Promise<IconChunkIndex> | undefined
  static #solidIndex: IconChunkIndex | undefined

  /**
   * Sorted words -> the ONE icon they name in any order, or `null` if 2+ icons share them
   * (`arrow-up-a-z` / `arrow-up-z-a`).
   * - Built on first use from the solid index + Font Awesome's aliases -- see `#reorder()`.
   */
  static #wordSets: Map<string, string | null> | undefined

  ////////////////
  // ## Name resolution
  ////////////////

  /**
   * Resolves a possibly-aliased, possibly-multi-word icon name to its canonical Font Awesome 7 name + style.
   * - Spaces ~== dashes:  `"tablet button"` ~== `"tablet-button"`,  `"sign-in"` ~== `"sign in"`.
   * - Order:  strip a trailing `outline` word (-> `style: "regular"`), then Fomantic's OWN alias vocabulary
   *   (`"mail"` -> `"envelope"`, `"setting"` -> `"gear"`), then Font Awesome's alias vocabulary
   *   (`"cog"` -> `"gear"`), then -- if `style` is still unknown -- checks the (lazily-loaded) solid index:
   *   present there => `solid`, otherwise => `brands`.  A name Font Awesome doesn't know at all resolves as
   *   `solid` anyway;  `get()` then correctly finds nothing and returns `undefined`.
   * - Last resort, word order:  a name found nowhere is tried in ANY order, if those words name exactly one
   *   icon -- `"button tablet"` -> `"tablet-button"` -- see `#reorder()`.
   * - `style`, whether passed in or inferred from `outline`, always wins over the solid/brands guess --
   *   a caller who says `{ style: "brands" }` is trusted, even for a name that also happens to exist elsewhere.
   * - A word that means different icons in the two vocabularies (`"x"`, `"warning"`, `"sign in"` ...)
   *   gets Font Awesome's meaning, unless the page opts into Fomantic's -- see `preferredNames`.
   */
  static async resolve(name: string, style?: IconStyle): Promise<IconResolved> {
    const partial = Icons.#resolveAliases(name, style)
    if (partial.style === "brands") return { name: partial.name, style: "brands" }
    const index = await Icons.#loadSolidIndex()
    const found = Icons.#reorder(partial.name, index)
    return { name: found, style: partial.style ?? (found in index ? "solid" : "brands") }
  }

  /**
   * `name`, or the one icon its words name in another order -- `"button-tablet"` -> `"tablet-button"`.
   * - Only for a name the solid index doesn't know:  an exact name, Fomantic alias or FA alias always wins.
   * - Ambiguous word sets (`a-z` vs `z-a`, `left-right` vs `right-left`) stay as typed, so they fail loudly
   *   rather than silently picking one.
   * - NOTE: covers solid + regular (every regular icon is also solid) and brands only through FA's aliases
   *   (`github-square` -> `square-github`) -- the full brand list lives in the 560 KB `brands.json`.
   *   `Icons.test.ts` checks no real brand name is ever redirected.
   */
  static #reorder(name: string, index: IconChunkIndex): string {
    if (name in index || !name.includes("-")) return name
    Icons.#wordSets ??= Icons.#buildWordSets(index)
    return Icons.#wordSets.get(Icons.#wordSet(name)) ?? name
  }

  /** `#wordSets` from every multi-word solid name and Font Awesome alias. */
  static #buildWordSets(index: IconChunkIndex): Map<string, string | null> {
    const sets = new Map<string, string | null>()
    const entries = [...Object.keys(index).map((key) => [key, key]), ...Object.entries(faAliases as IconAliasMap)]
    for (const [key, target] of entries) {
      if (!key.includes("-")) continue
      const words = Icons.#wordSet(key)
      const current = sets.get(words)
      sets.set(words, current === undefined || current === target ? target : null)
    }
    return sets
  }

  /** Order-free key for a dashed name:  its words, sorted -- `"tablet-button"` -> `"button tablet"`. */
  static #wordSet(name: string): string {
    return name.split("-").sort().join(" ")
  }

  /**
   * The synchronous, cache-only half of `resolve()` -- alias lookups only, no chunk loading.
   * - Shared by `resolve()` (which fills in a missing `style` with an async index check) and `peek()`
   *   (which instead leaves `style` unset when it can't answer without loading something).
   */
  static #resolveAliases(name: string, style: IconStyle | undefined): { name: string; style?: IconStyle } {
    const words = name
      .trim()
      .toLowerCase()
      .split(/[\s-]+/)
      .filter(Boolean)
    let resolvedStyle = style
    if (!resolvedStyle && words.at(-1) === "outline") {
      resolvedStyle = "regular"
      words.pop()
    }
    const phrase = words.join(" ")
    const kebab = words.join("-")
    const clash = Icons.preferredNames === "fomantic" ? (fomanticClashes as IconAliasMap)[phrase] : undefined
    const afterFomantic = clash ?? (fomanticAliases as IconAliasMap)[phrase] ?? kebab
    const canonical = (faAliases as IconAliasMap)[afterFomantic] ?? afterFomantic
    return { name: canonical, style: resolvedStyle }
  }

  /**
   * Which vocabulary wins a clash, read from `<html ui-icon-names>` on EVERY lookup.
   * - `"fontawesome"` unless the attribute says `"fomantic"`;  also outside a browser (no `document`).
   * - NOTE: flipping the attribute affects later lookups only -- icons already drawn keep their old meaning.
   */
  static get preferredNames(): IconNames {
    if (typeof document === "undefined") return "fontawesome"
    return document.documentElement.getAttribute(ICON_NAMES_ATTRIBUTE) === "fomantic" ? "fomantic" : "fontawesome"
  }

  ////////////////
  // ## Data access
  ////////////////

  /**
   * Resolves `name` and loads whichever chunk holds it (once per chunk, cached after), returning its
   * `[width, height, path]` tuple -- `undefined` for a name Font Awesome doesn't have in that style.
   */
  static async get(name: string, style?: IconStyle): Promise<IconData | undefined> {
    // An explicit style is trusted BEFORE aliasing:  `("apple", "brands")` means the Apple logo, not the
    // Fomantic alias `apple` -> `apple-whole` (solid), which has no brands entry at all.
    if (style) {
      const plain = await Icons.#lookup(Icons.#kebab(name), style)
      if (plain) return plain
    }
    const request = await Icons.resolve(name, style)
    return Icons.#lookup(request.name, request.style)
  }

  /** The chunk lookup behind `get()`:  loads the chunk holding `name` in `style`, returns its tuple. */
  static async #lookup(name: string, style: IconStyle): Promise<IconData | undefined> {
    const chunk = style === "solid" ? (await Icons.#loadSolidIndex())[name] : style
    if (!chunk) return undefined
    const data = await Icons.#loadChunk(chunk)
    return data[name]
  }

  /** `name` normalized the way the data files spell it:  lowercase words joined with `-`. */
  static #kebab(name: string): string {
    return name
      .trim()
      .toLowerCase()
      .split(/[\s-]+/)
      .filter(Boolean)
      .join("-")
  }

  /**
   * Synchronous counterpart to `get()`:  returns the tuple if its chunk has ALREADY been loaded (by an
   * earlier `get()` or `preload()`), `undefined` otherwise -- never triggers a fetch itself.
   * - Uses only the synchronous alias/style resolution:  if the style is still ambiguous (no explicit
   *   `style`, no `outline` word, and the solid index hasn't loaded yet to check), this returns `undefined`
   *   rather than guessing -- there's nothing in cache to answer from either way.
   */
  static peek(name: string, style?: IconStyle): IconData | undefined {
    if (style) {
      // same explicit-style-first rule as `get()`
      const chunk = style === "solid" ? Icons.#solidIndex?.[Icons.#kebab(name)] : style
      const plain = chunk ? Icons.#chunks.get(chunk)?.data?.[Icons.#kebab(name)] : undefined
      if (plain) return plain
    }
    const partial = Icons.#resolveAliases(name, style)
    const index = Icons.#solidIndex
    const found = index && partial.style !== "brands" ? Icons.#reorder(partial.name, index) : partial.name
    let resolvedStyle = partial.style
    if (!resolvedStyle) {
      if (!index) return undefined
      resolvedStyle = found in index ? "solid" : "brands"
    }
    const chunk = resolvedStyle === "solid" ? index?.[found] : resolvedStyle
    if (!chunk) return undefined
    return Icons.#chunks.get(chunk)?.data?.[found]
  }

  /** Warms the cache for `names` (each resolved with its default style) -- fire-and-forget from a component. */
  static async preload(names: readonly string[]): Promise<void> {
    await Promise.all(names.map((name) => Icons.get(name)))
  }

  /**
   * Every icon name available in `style`, for the docs site's icon browser.
   * - `async`, unlike a naive "just read the index" expectation:  `solid`'s names come from the (lazy)
   *   chunk index, `regular` / `brands`' names come from loading their one data file (there's no separate
   *   names-only manifest for those -- see `docs/icons.md`).
   */
  static async names(style: IconStyle): Promise<string[]> {
    if (style === "solid") return Object.keys(await Icons.#loadSolidIndex())
    return Object.keys(await Icons.#loadChunk(style))
  }

  ////////////////
  // ## Chunk loading
  ////////////////

  /** Loads (once) and caches `solid.json`, the `{ name: chunkFile }` index every solid-style lookup needs. */
  static async #loadSolidIndex(): Promise<IconChunkIndex> {
    Icons.#solidIndexLoader ??= import("./data/solid.json").then((module) => {
      const index = module.default as IconChunkIndex
      Icons.#solidIndex = index
      return index
    })
    return Icons.#solidIndexLoader
  }

  /** Loads (once) and caches one data chunk by file name (without `.json`), e.g. `"solid-a-c"`, `"brands"`. */
  static async #loadChunk(chunk: string): Promise<IconChunk> {
    const cached = Icons.#chunks.get(chunk)
    if (cached) return cached.promise
    // NOTE: `entry` is built before `promise` so the `.then()` closure can fill in `entry.data` once the
    // import settles -- `peek()` reads that same object back out of `#chunks`, no separate bookkeeping.
    const entry = {} as IconLoader
    entry.promise = import(`./data/${chunk}.json`).then((module) => {
      const data = module.default as IconChunk
      entry.data = data
      return data
    })
    Icons.#chunks.set(chunk, entry)
    return entry.promise
  }

  ////////////////
  // ## Rendering
  ////////////////

  /**
   * Builds an `<svg>` element for `data` (from `get()` / `peek()`):  its `viewBox` plus a single
   * `<path fill="currentColor">`, so CSS `color` drives the icon's colour same as text.
   * - No `label` (the common case, a purely decorative icon next to visible text) => `aria-hidden="true"`,
   *   so screen readers skip it.
   * - A `label` => `role="img"` + `aria-label`, making the icon itself the accessible name (for an icon-only
   *   control with no visible text).
   * - `title` adds an `<svg><title>` for a native tooltip -- independent of `label`, since a labelled icon
   *   can still want hover text.
   */
  static svg(data: IconData, options: { label?: string; title?: string } = {}): SVGSVGElement {
    const [width, height, path] = data
    const svg = document.createElementNS(SVG_NS, "svg")
    svg.setAttribute("viewBox", `0 0 ${width} ${height}`)
    if (options.label) {
      svg.setAttribute("role", "img")
      svg.setAttribute("aria-label", options.label)
    } else {
      svg.setAttribute("aria-hidden", "true")
    }
    if (options.title) {
      const title = document.createElementNS(SVG_NS, "title")
      title.textContent = options.title
      svg.append(title)
    }
    const path_ = document.createElementNS(SVG_NS, "path")
    path_.setAttribute("fill", "currentColor")
    path_.setAttribute("d", path)
    svg.append(path_)
    return svg
  }

  /**
   * `svg()`'s string equivalent, for templating into `innerHTML` -- e.g. a component's shadow-root template
   * literal, where creating a live element up front would be wasted work.
   * - Always `aria-hidden`:  a templated icon has no `label`/`title` slot -- a caller that needs those
   *   builds with `svg()` instead, or wraps the string in its own labelled container.
   * - Path data is digits / letters / spaces / punctuation only (SVG path grammar), never a quote or `<` --
   *   safe to inline without escaping.
   */
  static svgString(data: IconData): string {
    const [width, height, path] = data
    return `<svg viewBox="0 0 ${width} ${height}" aria-hidden="true"><path fill="currentColor" d="${path}"/></svg>`
  }
}
