/**
 * Every name `<ui-flag>` uses:  tag, attributes (kind + allowed values), parts, texts -- plus the country data
 * the element resolves `country` with.  Schema:  `ComponentVocabulary` (`$/ui/vocabulary`).
 * - Class words come out through `ClassBuilder`, in Fomantic's grammar:  `<ui-flag country="fr" size="large">`
 *   => `ui large flag`.  The country is CONTENT, not a class:  the Unicode flag emoji (`🇫🇷`), which is what
 *   Fomantic 2.9's default theme draws too (Twemoji SVGs named by the same code points).
 * - Resolving `country` (the element's job):
 *   - normalize:  trim, lowercase, `_` => space, collapse whitespace (`United_States` ~== `united states`)
 *   - `flagAliases[name] ?? name` => a code:  an ISO 3166-1 alpha-2 code, or a key of `flagEmoji`
 *   - `flagEmoji[code]`, else a two-letter code => its regional-indicator pair
 *     (`U+1F1E6 + letter - "a"` per letter:  `fr` => `🇫🇷`);  anything else renders an empty flag box
 *   - `aria-label`:  `texts` for the `flagEmoji` codes, else `Intl.DisplayNames(lang, { type: "region" })`
 *     of the upper-cased code (`FR` => `France`), which also follows the page language for free
 * - NOTE: aliases are Fomantic's English names;  a translation adds its own names next to them (they're data,
 *   not vocabulary names).
 */

import type { ComponentVocabulary } from "$/ui/vocabulary"

/****************
 * ### `<ui-flag>`
 * A country flag:  `<span class="ui [size] flag" part="flag" role="img" aria-label="France">🇫🇷</span>`.
 ****************/
export const flagVocabulary = {
  tag: "ui-flag",
  noun: "flag",
  description: "A flag is used to represent a political state.",
  attributes: [
    {
      name: "size",
      kind: "size",
      values: ["small", "medium", "large", "big", "huge", "massive"],
      description:
        "Fomantic's flag sizes against the surrounding text, `small` (1.5em) ... `massive` (12em);  `medium` " +
        "is the unsized default (1em), NOT Fomantic's 3em."
    },
    {
      name: "country",
      kind: "string",
      description:
        "ISO 3166-1 alpha-2 code in any case (`fr`, `US`), or one of Fomantic's names and aliases " +
        "(`france`, `united states`, `america`, `uk`, `england`, `pride` ...), see `flagAliases`."
    }
  ],
  events: [],
  slots: [],
  parts: [{ name: "flag", description: "The flag glyph box." }],
  states: [],
  texts: [
    { key: "rainbow", text: "Rainbow flag", description: "Label of `rainbow` (`pride`, `lgbt`)." },
    { key: "transgender", text: "Transgender flag", description: "Label of `transgender`." },
    { key: "pirate", text: "Pirate flag", description: "Label of `pirate`." },
    { key: "gbEng", text: "England", description: "Label of `gb-eng` (`england`)." },
    { key: "gbSct", text: "Scotland", description: "Label of `gb-sct` (`scotland`)." },
    { key: "gbWls", text: "Wales", description: "Label of `gb-wls` (`wales`)." }
  ]
} as const satisfies ComponentVocabulary

/**
 * Flags that aren't a regional-indicator pair, by code:  emoji ZWJ sequences, and the England / Scotland / Wales
 * subdivision flags (tag sequences named by their ISO 3166-2 codes, `gb-eng` ...).
 * - Why data:  the code => emoji rule only covers two-letter codes.
 * - NOTE: subdivision flags only render where the emoji font has them (Apple, Google, Samsung, Twemoji);
 *   Windows shows a black flag.
 */
export const flagEmoji = {
  rainbow: "\u{1F3F3}\u{FE0F}\u{200D}\u{1F308}",
  transgender: "\u{1F3F3}\u{FE0F}\u{200D}\u{26A7}\u{FE0F}",
  pirate: "\u{1F3F4}\u{200D}\u{2620}\u{FE0F}",
  "gb-eng": "\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  "gb-sct": "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  "gb-wls": "\u{1F3F4}\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}"
} as const satisfies Readonly<Record<string, string>>

/**
 * Fomantic's flag names and aliases (normalized:  lowercase, `_` => space) => code, from `flag.variables`.
 * - A code is an ISO 3166-1 alpha-2 code (lowercase) or a key of `flagEmoji`.
 * - Only names that differ from their code:  `fr` needs no entry.
 * - Two-letter aliases (`uk` => `gb`, `an` => `bq`) are looked up BEFORE the code rule, as in Fomantic.
 */
export const flagAliases = {
  pride: "rainbow",
  lgbt: "rainbow",
  afghanistan: "af",
  "aland islands": "ax",
  albania: "al",
  algeria: "dz",
  "american samoa": "as",
  andorra: "ad",
  angola: "ao",
  anguilla: "ai",
  antarctica: "aq",
  "antigua and barbuda": "ag",
  antigua: "ag",
  argentina: "ar",
  armenia: "am",
  aruba: "aw",
  australia: "au",
  austria: "at",
  azerbaijan: "az",
  bahamas: "bs",
  bahrain: "bh",
  bangladesh: "bd",
  barbados: "bb",
  belarus: "by",
  belgium: "be",
  belize: "bz",
  benin: "bj",
  bermuda: "bm",
  bhutan: "bt",
  bolivia: "bo",
  "bosnia and herzegovina": "ba",
  botswana: "bw",
  brazil: "br",
  "british indian ocean territory": "io",
  "british virgin islands": "vg",
  brunei: "bn",
  bulgaria: "bg",
  "burkina faso": "bf",
  burundi: "bi",
  cambodia: "kh",
  cameroon: "cm",
  canada: "ca",
  "canary islands": "ic",
  "cape verde": "cv",
  "caribbean netherlands": "bq",
  an: "bq",
  "netherlands antilles": "bq",
  "cayman islands": "ky",
  "central african republic": "cf",
  chad: "td",
  chile: "cl",
  china: "cn",
  "christmas island": "cx",
  "cocos islands": "cc",
  colombia: "co",
  comoros: "km",
  "congo brazzaville": "cg",
  "congo kinshasa": "cd",
  congo: "cd",
  "cook islands": "ck",
  "costa rica": "cr",
  "côte d’ivoire": "ci",
  croatia: "hr",
  cuba: "cu",
  curacao: "cw",
  cyprus: "cy",
  czechia: "cz",
  "czech republic": "cz",
  denmark: "dk",
  djibouti: "dj",
  dominica: "dm",
  "dominican republic": "do",
  ecuador: "ec",
  egypt: "eg",
  "el salvador": "sv",
  "equatorial guinea": "gq",
  eritrea: "er",
  estonia: "ee",
  ethiopia: "et",
  "european union": "eu",
  "falkland islands": "fk",
  "faroe islands": "fo",
  fiji: "fj",
  finland: "fi",
  france: "fr",
  "french guiana": "gf",
  "french polynesia": "pf",
  "french southern territories": "tf",
  "french territories": "tf",
  gabon: "ga",
  gambia: "gm",
  georgia: "ge",
  germany: "de",
  ghana: "gh",
  gibraltar: "gi",
  greece: "gr",
  greenland: "gl",
  grenada: "gd",
  guadeloupe: "gp",
  guam: "gu",
  guatemala: "gt",
  guernsey: "gg",
  guinea: "gn",
  "guinea-bissau": "gw",
  guyana: "gy",
  haiti: "ht",
  honduras: "hn",
  "hong kong sar china": "hk",
  "hong kong": "hk",
  hungary: "hu",
  iceland: "is",
  india: "in",
  indonesia: "id",
  iran: "ir",
  iraq: "iq",
  ireland: "ie",
  "isle of man": "im",
  israel: "il",
  italy: "it",
  jamaica: "jm",
  japan: "jp",
  jersey: "je",
  jordan: "jo",
  kazakhstan: "kz",
  kenya: "ke",
  kiribati: "ki",
  kosovo: "xk",
  kuwait: "kw",
  kyrgyzstan: "kg",
  laos: "la",
  latvia: "lv",
  lebanon: "lb",
  lesotho: "ls",
  liberia: "lr",
  libya: "ly",
  liechtenstein: "li",
  lithuania: "lt",
  luxembourg: "lu",
  "macao sar china": "mo",
  "republic of north macedonia": "mk",
  "north macedonia": "mk",
  macedonia: "mk",
  madagascar: "mg",
  malawi: "mw",
  malaysia: "my",
  maldives: "mv",
  mali: "ml",
  malta: "mt",
  "marshall islands": "mh",
  martinique: "mq",
  mauritania: "mr",
  mauritius: "mu",
  mayotte: "yt",
  mexico: "mx",
  micronesia: "fm",
  moldova: "md",
  monaco: "mc",
  mongolia: "mn",
  montenegro: "me",
  montserrat: "ms",
  morocco: "ma",
  mozambique: "mz",
  myanmar: "mm",
  burma: "mm",
  namibia: "na",
  nauru: "nr",
  nepal: "np",
  netherlands: "nl",
  "new caledonia": "nc",
  "new zealand": "nz",
  nicaragua: "ni",
  niger: "ne",
  nigeria: "ng",
  niue: "nu",
  "norfolk island": "nf",
  "north korea": "kp",
  "northern mariana islands": "mp",
  norway: "no",
  oman: "om",
  pakistan: "pk",
  palau: "pw",
  "palestinian territories": "ps",
  panama: "pa",
  "papua new guinea": "pg",
  "new guinea": "pg",
  paraguay: "py",
  peru: "pe",
  philippines: "ph",
  "pitcairn islands": "pn",
  poland: "pl",
  portugal: "pt",
  "puerto rico": "pr",
  qatar: "qa",
  réunion: "re",
  romania: "ro",
  russia: "ru",
  rwanda: "rw",
  samoa: "ws",
  "san marino": "sm",
  "sao tome and principe": "st",
  "samo tome": "st",
  "saudi arabia": "sa",
  saudiarabia: "sa",
  saudi: "sa",
  senegal: "sn",
  serbia: "rs",
  seychelles: "sc",
  "sierra leone": "sl",
  singapore: "sg",
  "sint maarten": "sx",
  slovakia: "sk",
  slovenia: "si",
  "south georgia and south sandwich islands": "gs",
  "sandwich islands": "gs",
  "solomon islands": "sb",
  somalia: "so",
  "south africa": "za",
  "south korea": "kr",
  "south sudan": "ss",
  spain: "es",
  "sri lanka": "lk",
  "st barthelemy": "bl",
  "saint barth": "bl",
  "st helena": "sh",
  "saint helena": "sh",
  "st kitts and nevis": "kn",
  "saint kitts and navis": "kn",
  "st lucia": "lc",
  "saint lucia": "lc",
  "st pierre and miquelon": "pm",
  "saint pierre": "pm",
  "st vincent and grenadines": "vc",
  sudan: "sd",
  suriname: "sr",
  eswatini: "sz",
  sweden: "se",
  switzerland: "ch",
  syria: "sy",
  taiwan: "tw",
  tajikistan: "tj",
  tanzania: "tz",
  thailand: "th",
  "timor-leste": "tl",
  togo: "tg",
  tokelau: "tk",
  tonga: "to",
  "trinidad and tobago": "tt",
  tunisia: "tn",
  turkey: "tr",
  turkmenistan: "tm",
  "turks and caicos islands": "tc",
  "us virgin islands": "vi",
  tuvalu: "tv",
  uganda: "ug",
  ukraine: "ua",
  "united arab emirates": "ae",
  uae: "ae",
  "united kingdom": "gb",
  uk: "gb",
  "gb eng": "gb-eng",
  england: "gb-eng",
  "gb sct": "gb-sct",
  scotland: "gb-sct",
  "gb wls": "gb-wls",
  wales: "gb-wls",
  "united states": "us",
  america: "us",
  uruguay: "uy",
  uzbekistan: "uz",
  vanuatu: "vu",
  "vatican city": "va",
  venezuela: "ve",
  vietnam: "vn",
  "wallis and futuna": "wf",
  "western sahara": "eh",
  yemen: "ye",
  zambia: "zm",
  zimbabwe: "zw",
  "ascension island": "ac",
  "bouvet island": "bv",
  "clipperton island": "cp",
  "ceuta and melilla": "ea",
  "diego garcia": "dg",
  "heard and mcdonald islands": "hm",
  "st martin": "mf",
  "svalbard and jan mayen": "sj",
  svalbard: "sj",
  "jan mayen": "sj",
  "tristan da cunha": "ta",
  "us outlying islands": "um",
  "minor islands": "um",
  "united nations": "un"
} as const satisfies Readonly<Record<string, string>>
