/**
 * `EmojiData`:  emoji names => native Unicode emoji, loaded lazily in chunks, from ONE name set at a time.
 * - Name sets (never merged):  `cldr`, the default (CLDR shortcodes, every emoji `emojibase-data` names:
 *   `thumbs_up`), and `fomantic` (Fomantic's own names with Fomantic's meanings:  `thumbsup`, `smile`, `dog` = 🐶).
 *   A translated set is another value of `names` (`es`, from emojibase's `es` data;  see `docs/translation.md`).
 * - Switching, page-wide:  `EmojiData.use("fomantic")` from JS, `<ui-emoji-set names="fomantic">` from HTML (the LAST
 *   one in the document, read at the first lookup, so it works before the element is defined;  one connected later
 *   calls `use()`).  Like icon packs, a switch affects LATER lookups only:  an emoji already drawn keeps its glyph.
 *   SSR / no `document`:  the default set, no DOM reads.
 * - Data:  `./data/<set>/<chunk>.json`, one per first letter of the name (`0` for a digit), generated by
 *   `scripts/gen-emoji.ts` from `emojibase-data` (a dev-only dependency) and Fomantic's `@emoji-map`;  a chunk is
 *   at most ~5 KB gzip.
 * - Loaded with `import()` on first use of a name in that chunk:  nothing is in `core` or in the emoji family's
 *   own chunk, and a page drawing `smile` fetches `s.json` only.  The module system is the cache;  a failed load
 *   is a miss until the next `get()` (no retry storm:  one import per chunk at a time).
 * - Library-neutral:  no Solid, so the native fallback uses it too.
 */

import {
  CAMEL,
  COLONS,
  DEFAULT_SET,
  DIGIT_CHUNK,
  LETTER,
  LOADERS,
  NAMES_ATTRIBUTE,
  SEPARATORS,
  SETS,
  SET_TAG,
  SPACES
} from "./ui-emoji.types"
export class EmojiData {
  /** The name set in use;  `undefined` until the first lookup (or `use()`) decides it. */
  private static set: string | undefined

  /** Loaded name => emoji, of the current set. */
  private static readonly cache = new Map<string, string>()

  /**
   * The same, keyed by `loose()`:  the fallback when the exact name misses.
   * - First name in wins;  chunks list names sorted, and `_` sorts before letters, so the underscored spelling wins
   *   a clash.  In `cldr` there is none;  in `fomantic`, `ice-cream` / `IceCream` ~== `ice_cream` 🍨, while an exact
   *   `icecream` stays 🍦.
   */
  private static readonly looseCache = new Map<string, string>()

  /** `register()`ed names:  they survive a switch and apply to any set, ahead of its own names. */
  private static readonly registered = new Map<string, string>()

  /** The same, keyed by `loose()`. */
  private static readonly registeredLoose = new Map<string, string>()

  /** `<set>/<chunk>` => its load, so each chunk is requested once at a time. */
  private static readonly loads = new Map<string, Promise<void>>()

  /** Chunks of the current set that are loaded. */
  private static readonly loaded = new Set<string>()

  /** The name set in use:  `cldr` unless `use()` or a `<ui-emoji-set>` in the document says otherwise. */
  static get names(): string {
    if (EmojiData.set === undefined) {
      if (typeof document === "undefined") return DEFAULT_SET
      EmojiData.set = EmojiData.valid(EmojiData.fromDocument())
    }
    return EmojiData.set
  }

  /**
   * Use name set `names` (`cldr` or `fomantic`;  an unknown one means the default) for every LATER lookup.
   * - Clears the loaded names of the old set;  `register()`ed names stay.  Emoji already drawn keep their glyph.
   */
  static use(names: string | undefined) {
    const set = EmojiData.valid(names)
    if (set === EmojiData.set) return
    EmojiData.set = set
    EmojiData.clear()
  }

  /** Forget the choice, so the next lookup reads the document again.  For tests and hot reload. */
  static reset() {
    EmojiData.set = undefined
    EmojiData.clear()
  }

  /**
   * Canonical form of a name as authors write it:  trimmed, Fomantic's `:colons:` stripped, camelCase split
   * (`thumbsUp`, from JS), lower case, runs of spaces => `_` (`Thumbs Up` ~== `thumbs_up`).  Dashes stay:  some names
   * have them (`blond-haired_woman`);  `loose()` drops them for the fallback.
   */
  static normalize(name: string): string {
    return name.trim().replace(COLONS, "").trim().replace(CAMEL, "$1_$2").toLowerCase().replace(SPACES, "_")
  }

  /**
   * A NORMALIZED name with no separators at all (`thumbsup`, `thumbs-up` => `thumbsup`):  the fallback key, so a name
   * works however its words are joined.  In the data, names that differ only in separators mean the same
   * emoji, except Fomantic's `icecream` (see `looseCache`).
   */
  static loose(name: string): string {
    return name.replace(SEPARATORS, "")
  }

  /** Chunk key of a NORMALIZED name:  its first letter, else `0`.  MUST match `scripts/gen-emoji.ts`. */
  static chunkOf(name: string): string {
    const first = name[0] ?? ""
    return LETTER.test(first) ? first : DIGIT_CHUNK
  }

  /** The emoji for `name` if it's already known (loaded or registered), else `undefined`.  Synchronous. */
  static peek(name: string | undefined): string | undefined {
    return name ? EmojiData.known(EmojiData.normalize(name)) : undefined
  }

  /**
   * The emoji for `name`, loading its chunk if needed;  `undefined` for an unknown name.  Never rejects.
   * - SIDE EFFECT:  caches the whole chunk.
   */
  static async get(name: string | undefined): Promise<string | undefined> {
    if (!name) return undefined
    const key = EmojiData.normalize(name)
    const known = EmojiData.known(key)
    if (known !== undefined || !key) return known
    const chunk = EmojiData.chunkOf(key)
    if (!EmojiData.loaded.has(chunk)) await EmojiData.load(chunk)
    return EmojiData.known(key)
  }

  /** Add (or override) one emoji without a request, e.g. an app's own name for a sequence.  Applies to any set. */
  static register(name: string, emoji: string) {
    const key = EmojiData.normalize(name)
    EmojiData.registered.set(key, emoji)
    EmojiData.registeredLoose.set(EmojiData.loose(key), emoji)
  }

  /** Forget the loaded names of the old set. */
  private static clear() {
    EmojiData.cache.clear()
    EmojiData.looseCache.clear()
    EmojiData.loaded.clear()
  }

  /** A NORMALIZED name's emoji:  registered first, then the exact name, else the same words joined any way. */
  private static known(key: string): string | undefined {
    // NOTE:  `names` decides the set on the first lookup, before the caches are read
    void EmojiData.names
    const loose = EmojiData.loose(key)
    return (
      EmojiData.registered.get(key) ??
      EmojiData.cache.get(key) ??
      EmojiData.registeredLoose.get(loose) ??
      EmojiData.looseCache.get(loose)
    )
  }

  /** `names` of the last `<ui-emoji-set>` in the document, if any. */
  private static fromDocument(): string | undefined {
    const sets = document.querySelectorAll(SET_TAG)
    return sets[sets.length - 1]?.getAttribute(NAMES_ATTRIBUTE) ?? undefined
  }

  /** `names` if it is a set we ship data for, else the default. */
  private static valid(names: string | undefined): string {
    const set = names?.trim().toLowerCase()
    return set && SETS.has(set) ? set : DEFAULT_SET
  }

  /**
   * Where a chunk's names come from instead of this module's own lazy `import()`s:  `(set, chunk) => names`.
   * - For a build that can't load ES modules lazily, e.g. the docs' single-file bundle on `file://`, which loads each
   *   chunk as a classic `<script>` (`packages/docs/scripts/bundle-spell-ui.js`).  Set it before the first lookup.
   */
  static chunkLoader?: (set: string, chunk: string) => Promise<Record<string, string>>

  /** Load chunk `chunk` of the current set once;  a failure is forgotten, so a later `get()` tries again. */
  private static load(chunk: string): Promise<void> {
    const set = EmojiData.names
    const id = `${set}/${chunk}`
    let load = EmojiData.loads.get(id)
    if (!load) {
      const own = LOADERS[`./data/${id}.json`]
      if (!own) return Promise.resolve()
      const names = EmojiData.chunkLoader ? EmojiData.chunkLoader(set, chunk) : own().then((module) => module.default)
      load = names
        .then((data) => {
          // a switch while loading:  these names belong to the old set
          if (EmojiData.set !== set) return
          for (const [name, emoji] of Object.entries(data)) {
            if (!EmojiData.cache.has(name)) EmojiData.cache.set(name, emoji)
            const loose = EmojiData.loose(name)
            if (!EmojiData.looseCache.has(loose)) EmojiData.looseCache.set(loose, emoji)
          }
          EmojiData.loaded.add(chunk)
        })
        .catch(() => undefined)
        .finally(() => EmojiData.loads.delete(id))
      EmojiData.loads.set(id, load)
    }
    return load
  }
}
