// GENERATED by `scripts/gen-icons.ts` -- do not hand edit.  See `docs/icons.md`.
// One arrow per data chunk, so a bundler sees each file as its own lazy import target instead of
// gluing every `data/*.json` file (including `search.json`, which nothing loads) into one glob.
export const CHUNK_LOADERS: Readonly<Record<string, () => Promise<unknown>>> = {
  "brands": () => import("./brands.json"),
  "regular": () => import("./regular.json"),
  "solid-0-b": () => import("./solid-0-b.json"),
  "solid-b-c": () => import("./solid-b-c.json"),
  "solid-ba-bu": () => import("./solid-ba-bu.json"),
  "solid-c-d": () => import("./solid-c-d.json"),
  "solid-d-f": () => import("./solid-d-f.json"),
  "solid-f-g": () => import("./solid-f-g.json"),
  "solid-g-h": () => import("./solid-g-h.json"),
  "solid-h-j": () => import("./solid-h-j.json"),
  "solid-k-m": () => import("./solid-k-m.json"),
  "solid-m-p": () => import("./solid-m-p.json"),
  "solid-pe-pu": () => import("./solid-pe-pu.json"),
  "solid-q-s": () => import("./solid-q-s.json"),
  "solid-s-t": () => import("./solid-s-t.json"),
  "solid-t-u": () => import("./solid-t-u.json"),
  "solid-u-w": () => import("./solid-u-w.json"),
  "solid-w-z": () => import("./solid-w-z.json")
}
