// Icon pack index, generated by `IconPackBuilder` (`docs/icons.md`).
// Safe to hand-edit:  re-running the builder keeps each entry's `alias` and other fields, refreshing only sizes.
export default {
  id: "stroke",
  label: "Stroke fixture",
  defaults: { width: 24, height: 24 },
  icons: {
    bell: {},
    sun: { alias: ["light", "day"] }
  }
}
