//  # Parser Rules
//

import { Derivative } from "~/util/Derivative"
import { P } from "~/parser"

/**
 * # Rule base class
 * Rules can be as simple as a string `Keyword` or a complex sequence of recursive rules.
 *
 *  Parse a rule with `rule.parse(scope, tokens)`.
 *  - If **successful**, it will return a new `Match()` object.
 *  - If **unsuccessful**, it will return `undefined`
 *
 * The `match` object links the tokens actually matched with the matched rule, and has properties:
 *    - `match.rule`        : pointer back to the matched rule.
 *    - `match.scope`       : the scope in which the rule was matched.
 *    - `match.matched`     : array of *significant* tokens that were actually matched.
 *    - `match.tokens`      : array of all tokens that were consumed.
 *    - `match.value`       : the "value" of the match, which is rule-specific.
 *    ... and other rule-specific values.
 *
 *  To output the result of a match, use `match.compile()` which calls `rule.compile()`
 *  to actually generate the output.
 */
export abstract class Rule<Props extends RuleProps = RuleProps> extends Derivative {
  /** ---------------
   * ## Properties
   *  --------------- */
  /** Name of source file this rule was defined in. */
  declare module: string | undefined
  /** Rule name, must be unique if defined. */
  declare name: string | undefined
  /** Description of this rule. */
  declare description: string | undefined
  /** Name aliases -- indicates this rules works a part of collections such as `expression` or `statement`. */
  declare alias: string | string[] | undefined
  /** Precedence of this rule, used to distinguish between ambiguous matches.  Default = 0. */
  declare precedence: number
  /** Datatype which rule result represents, e.g. `string`, `number`, custom type. */
  declare datatype: string | undefined
  /** Rulex syntax string(s) used to define this rule. */
  declare syntax: string | string[] | undefined
  /** Test rule to use to quickly determine if this rule can be matched. */
  declare testRule: Rule | undefined
  /** Test location to use to determine if this rule can be matched. */
  declare testLocation: P.TestLocation | undefined
  /** Name for this rule in `match.groups`. */
  // REFACTOR: `groupName`
  declare argument: string | undefined
  /** Whether this rule is optional. */
  declare optional: boolean | undefined
  /** Whether this rule is left-recursive (e.g. `{expression} + {expression}`). */
  declare isLeftRecursive: boolean | undefined
  /** Tests for this rule. */
  declare tests: P.RuleTests | undefined
  /** Scope of this rule. */
  // TODO: why is this needed?
  declare scope: P.Scope | undefined

  // Define properties on prototype to keep instances as small as possible
  // and so that `Object.keys()` only returns properties defined in the instance.
  static {
    Object.defineProperty(this.prototype, "precedence", { value: 0, writable: true })
    // Object.defineProperty(this.prototype, "module", { writable: true })
    // Object.defineProperty(this.prototype, "name", { writable: true })
    // Object.defineProperty(this.prototype, "description", { writable: true })
    // Object.defineProperty(this.prototype, "alias", { writable: true })
    // Object.defineProperty(this.prototype, "datatype", { writable: true })
    // Object.defineProperty(this.prototype, "syntax", { writable: true })
    // Object.defineProperty(this.prototype, "testRule", { writable: true })
    // Object.defineProperty(this.prototype, "testLocation", { writable: true })
    // Object.defineProperty(this.prototype, "argument", { writable: true })
    // Object.defineProperty(this.prototype, "optional", { writable: true })
    // Object.defineProperty(this.prototype, "tests", { writable: true })
    // Object.defineProperty(this.prototype, "scope", { writable: true })
  }

  // props: Record<string,any>
  constructor(props?: Props) {
    super()
    if (props) Object.assign(this, props)
  }

  /** Return a clone of this rule (same constructor, all public properties). */
  clone() {
    const constructor = this.constructor as new (props?: any) => typeof this
    return new constructor(this)
  }

  /** Return array of `names` for this rule:  its `.name` + any `.alias`es. */
  get names() {
    let { alias = [] } = this
    if (typeof alias === "string") alias = [alias]
    return [this.name, ...alias].filter((it) => it !== undefined)
  }

  ////////////////////
  // ## Parsing methods -- implement these in your subclasses!
  ////////////////////

  /**
   * Attempt to match this rule at the start of `tokens`.
   * - If successful, returns a `Match` object which you can use to `compile()` the results.
   * - If unsuccessful, returns `undefined`.
   */
  abstract parse(scope: P.Scope, tokens: P.Token[]): P.Match | undefined

  /**
   * Output for this rule passed a successful `match` generated by it.
   * You may want to look at `match.matched` or `match.results`, etc.
   * - Language parsers generally return javascript source as a string.
   * - Other parsers (e.g. `rulex`) return arbitrary values, e.g. `Rule` instances.
   */
  abstract compile(match: P.AnyMatch): unknown

  /**
   * Some parsers compile by generating an "Abstract Syntax Tree" (AST) first,
   * then calling `AST.compile()`.
   *
   * If you implement this, return an `ASTNode` object (or `undefined` if the match yields no output).
   */
  getAST?(match: P.AnyMatch): P.ASTNode | undefined

  ////////////////////
  // ## Quick testing methods
  ////////////////////

  /**
   * Test to see if this rule is matched in `tokens`.
   *
   * You shouldn't override this, override `testAtStart()` instead,
   * or just provide a `testRule`.
   *
   * - By default, we respect our `testLocation` parameter to test
   *   either at the beginning of the tokens or anywhere in the run.
   * - Pass in specific `testLocation` to override the `testLocation` at runtime.
   */
  test(scope: P.Scope, tokens: P.Token[], testLocation = this.testLocation): boolean | undefined {
    if (!tokens.length) return false
    if (this.testRule) return this.testRule.test(scope, tokens, testLocation)

    if (testLocation === P.TestLocation.ANYWHERE) return this.testAnywhere(scope, tokens)
    return this.testAtStart(scope, tokens, 0)
  }

  /**
   * Test to see if there is ANY WAY that we can be found
   * starting at `start` position of `tokens`.
   *
   * This is used to exit quickly if there is no chance of success,
   * and is especially useful for rules which call themselves recursively.
   *
   * Returns:
   *  - `true` if the rule MIGHT be matched.
   *  - `false` if there is NO WAY the rule can be matched.
   *  - `undefined` if not determinstic (eg: no way to tell quickly).
   */
  testAtStart(scope: P.Scope, tokens: P.Token[], start = 0): boolean | undefined {
    if (start >= tokens.length) return false
    if (this.testRule) return this.testRule.testAtStart(scope, tokens, start)
    return undefined
  }

  /**
   * Test if this rule is matched anywhere in the tokens
   * by exhaustively testing at each start position.
   *
   * - This might be less efficient than just trying to match the rule itself!
   */
  testAnywhere(scope: P.Scope, tokens: P.Token[]): boolean | undefined {
    let undefinedFound = false
    for (let start = 0, last = tokens.length; start < last; start++) {
      const result = this.testAtStart(scope, tokens, start)
      if (result) return true
      if (result === undefined) undefinedFound = true
    }
    if (undefinedFound) return undefined
    return false
  }

  ////////////////////
  // ## Match groups & scopes
  ////////////////////

  /**
   * Return match `groups` for this match.
   * - Some rules derive additional groups based on analysis of "normal" groups.
   * - NOTE: always use `match.groups` to access so we re-use the same `groups` object.
   */
  getGroupsForMatch(match: P.AnyMatch): Record<string, unknown> {
    return match.addMatchedToGroups<P.MatchGroups>({}, [match])
  }

  /**
   * Return `scope` to use to parse "nested" contents of the match,
   * - By default, we just return the `match.scope`, but some rules may derive a new scope.
   * - For example, matching a method signature will define a nested MethodScope to compile the method body
   *   which includes the method arguments.
   * - NOTE: always use `match.nestedScope` to access so we re-use the scope object.
   */
  getNestedScopeForMatch(match: P.AnyMatch): P.Scope {
    return match.scope
  }

  /**
   * Mutate `match.scope` based on the semantics for this rule..
   * - By default, we don't change anything, but some rules
   *   may add new variables, methods, rules, etc. to the scope.
   */
  mutateScope(match: P.AnyMatch) {}

  ////////////////////
  // ## Rulex syntax
  ////////////////////

  /**
   * We attempt to merge literals or sequences together when creating rules.
   * We can only do that for rules that are not "adorned" with argument, etc.
   * - Note that `optional` doesn't matter in this case, because we can merge
   *   optional and non-optional rules.
   */
  // DEPRECATED
  get isAdorned() {
    return !!(this.argument || this.testLocation)
  }

  /** Return rulex string for this rule. */
  toRulexSyntax(): string {
    return ""
  }

  /** Return rulex syntax strings for rule flags. */
  getRulexFlags(): P.SyntaxFlags {
    const { testLocation, argument, optional } = this
    return {
      testLocation:
        testLocation === P.TestLocation.AT_START ? "…" : testLocation === P.TestLocation.ANYWHERE ? "^" : "",
      argument: argument ? ":" : "",
      optional: optional ? "?" : ""
    }
  }
}

export type RuleProps = {
  module?: string
  name?: string
  description?: string
  alias?: string | string[]
  datatype?: string
  syntax?: string | string[]
  precedence?: number
  testRule?: Rule
  testLocation?: P.TestLocation
  tests?: P.RuleTests
  scope?: P.Scope

  argument?: string
  optional?: boolean
  isEscaped?: boolean
  isLeftRecursive?: boolean
}
